name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
    - 'queue_python/'
    - '.github/workflows/test_queue_python.yml'
  
  pull_request:
    branches: [ master ]
    paths:
    - 'queue_python/'
    - '.github/workflows/test_queue_python.yml'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the queue_python image
      run: docker build -f queue_python/Dockerfile queue_python/ -t queue_python:${GITHUB_SHA}
